
stages:
  - production

before_script:
  image: node:16.15.0
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - npm install
  - cd client
  - npm install
  - cd ..

production:
  stage: production
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - main
