stages:
  - production

dependency:
  image: node:16.15.0
  before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl

production:
  stage: production
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - main
