// Alert
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

// Bidder
export const B_REGISTER_SUCCESS = "B_REGISTER_SUCCESS";
export const B_REGISTER_FAIL = "B_REGISTER_FAIL";
export const B_LOADED = "B_LOADED";
export const B_AUTH_ERROR = "B_AUTH_ERROR";
export const B_LOGIN_SUCCESS = "B_LOGIN_SUCCESS";
export const B_LOGIN_FAIL = "B_LOGIN_FAIL";
export const B_LOGOUT = "B_LOGOUT";

export const GET_B_PROFILE = "GET_B_PROFILE";
export const UPDATE_B_PROFILE = "UPDATE_B_PROFILE";
export const UPDATE_B_PROFILE_FAIL = "UPDATE_B_PROFILE_FAIL";
export const GET_B_HISTORY = "GET_B_HISTORY";

export const GET_AUCTIONS = "GET_AUCTIONS";
export const REGISTER_AUCTION = "REGISTER_AUCTION";
export const MARKET_PLACE = "MARKET_PLACE";
export const BID_PLACED = "BID_PLACED";

// Farmer
export const F_REGISTER_SUCCESS = "F_REGISTER_SUCCESS";
export const F_REGISTER_FAIL = "F_REGISTER_FAIL";
export const F_LOADED = "F_LOADED";
export const F_AUTH_ERROR = "F_AUTH_ERROR";
export const F_LOGIN_SUCCESS = "F_LOGIN_SUCCESS";
export const F_LOGIN_FAIL = "F_LOGIN_FAIL";
export const F_LOGOUT = "F_LOGOUT";

export const GET_F_PROFILE = "GET_F_PROFILE";
export const UPDATE_F_PROFILE = "UPDATE_F_PROFILE";
export const UPDATE_F_PROFILE_FAIL = "UPDATE_F_PROFILE_FAIL";

export const GET_F_HISTORY = "GET_F_HISTORY";

export const CREATE_AUCTION = "CREATE_AUCTION";
export const GET_F_CROPS = "GET_F_CROPS";
export const END_BIDDING = "END_BIDDING";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const SMS_SEND = "SMS_END";
export const EMAIL_SEND = "EMAIL_END";

export const OTP_SEND = "OTP_SEND";
export const OTP_VERIFY = "OTP_VERIFY";
export const CHANGE_MOBILE = "CHANGE_MOBILE";
export const CLEAR_OTP_STATE = "CLEAR_OTP_STATE";
